### ISSUE TITLE
please add Hikvision DS-2CD2135F-IWS to supported camear to wiki

### ISSUE THREAD

**Issue by mrproper** [moeiscool/Shinobi#21]
Manufacturer: HikVision
Model: DS-2CD2135F-IWS

Resolution: 2048x1536
Type: H264 (camera supports h265 and h265+ but they dont seem to work correctly with shinobi...green artifacts)
Stream URL: /Streaming/Channels/1?tcp
Save To: MP4 (I couldnt get webm to work)

**Comment by moeiscool** [comment]
thank you for the entry :)

do any of your cameras save to webm? this was happening on another system. it turned out ffmpeg didn't install with libvpx (VP8/VP9 encoder).

perhaps trying to install the latest `libav-tools` will solve the issue?

If you want you can join me on Discord https://discord.gg/mdhmvuH and we can try and hash it out 1-1

**Comment by moeiscool** [comment]
Camera added.
