### ISSUE TITLE
Possibly not an issue

### ISSUE THREAD

**Issue by danmed** [moeiscool/Shinobi#210]
I'm having some problems getting the detection level right.. however what i've noticed is that when the camera detects and starts recording, if i go in to the settings, the mode has changed to record.. if i alter something without noticing this and save, then the setting seems to be set at "record" again rather than "watch only"...

**Comment by moeiscool** [comment]
yes i guess this can be seen as bug in human logic.. The app itself see this as acceptable because "a human says so". It already has the order queued for it to return to its original mode. It forgets this order when a human hits save. I've designed it to take human input with more priority.

You can either use "Delete Motionless Video" (this may not be in master yet) or not hit save while its in a triggered state.
