### ISSUE TITLE
Deliber Shinobi in a package (Linux friendly way)

### ISSUE THREAD

**Issue by pabloab** [moeiscool/Shinobi#63]
Please consider making a deb/rpm (or even snap) Shinobi package. Maybe also a Launchpad PPA.

**Comment by moeiscool** [comment]
Sounds like a good idea. Sadly I have no clue on how to do these things yet :sweat_smile:. Are you having trouble installing? I can give you a hand on Slack.

For future suggestions please post on Slack in the #suggestions channel. https://shinobicctv.herokuapp.com/

 Since this is a suggestion I am going to close this thread. Thank you for trying Shinobi! :smile:
